repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs-js/blob/main
repository: dynamsoft-docs/capture-vision-docs-js
docFullPath: https://www.dynamsoft.com/capture-vision2/docs/
firstLevelUrl: /capture-vision2/docs/
docHomePage: /capture-vision2/docs/introduction/

introduction: /capture-vision2/docs/introduction/
architecture: /capture-vision2/docs/architecture/
parameter: /capture-vision2/docs/parameters/
parameterFile: /capture-vision2/docs/parameters/file/
parameterReference: /capture-vision2/docs/parameters/reference/

assets: /capture-vision2/docs/assets/
edit_icon: /capture-vision2/docs/assets/img-icon/edit-icon.png
smile_icon: /capture-vision2/docs/assets/img-icon/icon-smile.png
sad_icon: /capture-vision2/docs/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision2/docs/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision2/docs/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision2/docs/assets/img-icon/icon-dnt.svg

useVersionTree: true

baseurl: "/capture-vision2/docs"
plugins:
  - jemoji

url: "https://www.dynamsoft.com" # sitemap root

