repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs-js/blob/main
repository: dynamsoft-docs/capture-vision-docs-js
docFullPath: https://www.dynamsoft.com/capture-vision/docs/web/
firstLevelUrl: /capture-vision/docs/web/
docHomePage: /capture-vision/docs/web/introduction/

architecture: /capture-vision/docs/core/architecture/
parameter: /capture-vision/docs/core/parameters/
parameterFile: /capture-vision/docs/core/parameters/file/
parameterReference: /capture-vision/docs/core/parameters/reference/

js: /capture-vision/docs/web/programming/javascript/
js_api: /capture-vision/docs/web/programming/javascript/api-reference/

enums: /capture-vision/docs/web/programming/javascript/api-reference/enums/
 
assets: /capture-vision/docs/web/assets/
edit_icon: /capture-vision/docs/web/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/web/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/web/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/web/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/web/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/web/assets/img-icon/icon-dnt.svg

useVersionTree: true

baseurl: "/capture-vision/docs/web"
plugins:
  - jemoji

url: "https://www.dynamsoft.com" # sitemap root

